-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE POLICY "Owners and Admins can update teams"
    ON public.teams
    AS PERMISSIVE
    FOR UPDATE
    TO public
    USING ((auth.uid() IN ( SELECT members.user_id
   FROM members
  WHERE ((members.team_id = teams.id) AND ((members.permission_level = 'OWNER'::team_permission) OR (members.permission_level = 'ADMIN'::team_permission))))));
