-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.get_team_members(
	team_id_input uuid)
    RETURNS SETOF profiles 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$

declare
begin
    return query
        SELECT *
        FROM members
                 inner join teams ON teams.id = members.team_id
                 inner join profiles ON profiles.id = members.user_id
        WHERE team_id = team_id_input;
end;
$BODY$;

ALTER FUNCTION public.get_team_members(uuid)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.get_team_members(uuid) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.get_team_members(uuid) TO anon;

GRANT EXECUTE ON FUNCTION public.get_team_members(uuid) TO authenticated;

GRANT EXECUTE ON FUNCTION public.get_team_members(uuid) TO postgres;

GRANT EXECUTE ON FUNCTION public.get_team_members(uuid) TO service_role;
