-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.add_team(
	tid text,
	name text,
	user_id uuid)
    RETURNS uuid
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$

declare
    new_team_id uuid;
begin
    insert into teams(tid, name)
    values (add_team.tid, add_team.name)
    returning id into new_team_id;

    insert into members(team_id, user_id, permission_level)
    values (new_team_id, add_team.user_id, 'owner');

    return new_team_id;
end;
$BODY$;

ALTER FUNCTION public.add_team(text, text, uuid)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.add_team(text, text, uuid) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.add_team(text, text, uuid) TO anon;

GRANT EXECUTE ON FUNCTION public.add_team(text, text, uuid) TO authenticated;

GRANT EXECUTE ON FUNCTION public.add_team(text, text, uuid) TO postgres;

GRANT EXECUTE ON FUNCTION public.add_team(text, text, uuid) TO service_role;

ALTER TABLE IF EXISTS public.teams
    DISABLE ROW LEVEL SECURITY;
