-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- Type: team_permission

-- DROP TYPE IF EXISTS public.team_permission;

CREATE TYPE public.team_permission AS ENUM
    ('owner', 'user');

ALTER TYPE public.team_permission
    OWNER TO postgres;

CREATE TABLE IF NOT EXISTS public.members
(
    team_id          uuid            NOT NULL,
    user_id          uuid            NOT NULL,
    permission_level team_permission NOT NULL DEFAULT 'user'::team_permission,
    CONSTRAINT team_profile_pkey PRIMARY KEY (team_id, user_id),
    CONSTRAINT members_team_id_fkey FOREIGN KEY (team_id)
        REFERENCES public.teams (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT members_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.members
    OWNER to postgres;

GRANT ALL ON TABLE public.members TO anon;

GRANT ALL ON TABLE public.members TO authenticated;

GRANT ALL ON TABLE public.members TO postgres;

GRANT ALL ON TABLE public.members TO service_role;

COMMENT ON COLUMN public.members.permission_level
    IS 'The permission level of the membership.';
