-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

DROP FUNCTION IF EXISTS public.get_team_members(team_id_input uuid);

CREATE OR REPLACE FUNCTION public.get_team_members(IN team_id_input uuid)
    RETURNS TABLE(uid text, name text, avatar_url text, permission_level team_permission)
    LANGUAGE 'plpgsql'
    VOLATILE
    PARALLEL UNSAFE
    COST 100    ROWS 1000 
    
AS $BODY$

declare
begin
    return query
        SELECT profiles.uid, profiles.name, profiles.avatar_url, members.permission_level
        FROM members
                 inner join teams ON teams.id = members.team_id
                 inner join profiles ON profiles.id = members.user_id
        WHERE team_id = team_id_input;
end;
$BODY$;
