-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

DROP FUNCTION IF EXISTS public.get_team_members(team_id_input uuid);

DROP FUNCTION IF EXISTS public.add_team(tid text, name text, user_id uuid);

ALTER TABLE IF EXISTS public.members DROP COLUMN IF EXISTS permission_level;

CREATE POLICY "Enable access for authenticated users"
    ON public.members
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Enable access to all users" ON public.members;

DROP TYPE IF EXISTS public.team_permission;

CREATE TYPE public.team_permission AS ENUM ('OWNER', 'MEMBER', 'INVITED');

ALTER TYPE public.team_permission OWNER TO postgres;

ALTER TABLE IF EXISTS public.members
    ADD COLUMN permission_level team_permission NOT NULL DEFAULT 'OWNER'::team_permission;
