-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

DROP TABLE IF EXISTS public.teams CASCADE;

CREATE TABLE IF NOT EXISTS public.teams
(
    id         uuid                              NOT NULL DEFAULT uuid_generate_v4(),
    tid        text COLLATE pg_catalog."default" NOT NULL,
    name       text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone          NOT NULL DEFAULT now(),
    CONSTRAINT teams_pkey PRIMARY KEY (id),
    CONSTRAINT teams_tid_key UNIQUE (tid)
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.teams
    OWNER to postgres;

ALTER TABLE IF EXISTS public.teams
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.teams TO anon;

GRANT ALL ON TABLE public.teams TO authenticated;

GRANT ALL ON TABLE public.teams TO postgres;

GRANT ALL ON TABLE public.teams TO service_role;

COMMENT ON TABLE public.teams
    IS 'All the agity teams';