-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.profiles
    OWNER TO postgres;

REVOKE ALL ON TABLE public.profiles FROM anon;
REVOKE ALL ON TABLE public.profiles FROM authenticated;
REVOKE ALL ON TABLE public.profiles FROM postgres;
REVOKE ALL ON TABLE public.profiles FROM service_role;
REVOKE ALL ON TABLE public.profiles FROM supabase_admin;
GRANT ALL ON TABLE public.profiles TO anon;

GRANT ALL ON TABLE public.profiles TO authenticated;

GRANT ALL ON TABLE public.profiles TO postgres;

GRANT ALL ON TABLE public.profiles TO service_role;

ALTER TABLE IF EXISTS public.profiles
    DROP COLUMN IF EXISTS username;

ALTER TABLE IF EXISTS public.profiles
    DROP COLUMN IF EXISTS displayname;

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN name text COLLATE pg_catalog."default" DEFAULT 'Anonymous'::text;

COMMENT ON COLUMN public.profiles.name
    IS 'The display name of the user.';

ALTER TABLE IF EXISTS public.profiles
    ADD COLUMN uid text COLLATE pg_catalog."default" NOT NULL;

COMMENT ON COLUMN public.profiles.uid
    IS 'The users unique uid.';
ALTER TABLE IF EXISTS public.profiles
    ADD CONSTRAINT profiles_username_key UNIQUE (uid);

ALTER TABLE IF EXISTS public.profiles
    ADD CONSTRAINT username_length CHECK (char_length(uid) >= 3);
